# Generated by Django 5.1.15 on 2026-09-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_user_data_to_patient_record(apps, schema_editor):
    """Historical data preservation for the role refactor (patients -> records).

    Legacy PatientProfile rows were tied 1:1 to an authenticating PATIENT user.
    Before dropping that dependency this step copies the user's identity fields
    (full name, email, phone) directly onto the standalone patient record so no
    clinical/historical information is lost when the FK is removed.

    PatientProfile ids, patient codes and every downstream row (assessments,
    predictions, alerts, reports, chat sessions, audit entries that reference
    the patient) are untouched.
    """
    User = apps.get_model("accounts", "User")
    PatientProfile = apps.get_model("patients", "PatientProfile")

    profiles = list(PatientProfile.objects.select_related("user").all())
    for profile in profiles:
        user = profile.user
        if user is None:
            continue
        profile.full_name = profile.full_name or user.full_name or ""
        profile.email = profile.email or user.email or ""
        profile.phone = profile.phone or user.phone or ""
        profile.save(update_fields=["full_name", "email", "phone"])


def noop(apps, schema_editor):
    """Reverse is intentionally a no-op: the standalone record is authoritative."""


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Healthcare worker or admin who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unselect to archive (never delete history).'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='obstetric_history_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.RunPython(copy_legacy_user_data_to_patient_record, noop),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_by'], name='patients_pa_created_d6f646_idx'),
        ),
    ]
