# Generated by Django 5.1.15 on 2026-09-06 12:50

from django.db import migrations, models


def deactivate_legacy_patient_accounts(apps, schema_editor):
    """Retire legacy PATIENT accounts safely.

    Pre-migration installations contain real accounts with role='PATIENT'.
    Their associated clinical data is preserved on the standalone patient
    records (see patients.0002 data migration); the accounts themselves are
    only deactivated - never deleted - so audit history and foreign keys stay
    valid. Deactivated accounts plus the login/refresh role guard make patient
    authentication impossible after migration.
    """
    User = apps.get_model("accounts", "User")
    legacy = User.objects.filter(role="PATIENT")
    legacy.update(is_active=False)


def noop(apps, schema_editor):
    """Reverse is a no-op: we never restore deleted patient roles."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEALTHCARE_WORKER', 'Healthcare worker'), ('ADMIN', 'Administrator')], default='HEALTHCARE_WORKER', max_length=32),
        ),
        migrations.RunPython(deactivate_legacy_patient_accounts, noop),
    ]
