# Generated by Django 6.1 on 2026-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. RandomForest, XGBoost', max_length=64)),
                ('version', models.CharField(max_length=16)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.CharField(help_text='md5 of the training CSV', max_length=64)),
                ('features', models.JSONField(default=list)),
                ('training_config', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict, help_text='Test-split metrics')),
                ('validation_metrics', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=512)),
                ('selection_criterion', models.CharField(default='high_risk_recall_then_f1', max_length=64)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('PRODUCTION', 'Production'), ('RETIRED', 'Retired')], default='CANDIDATE', max_length=16)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['status'], name='mlcore_mode_status_d15d68_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
