# Generated by Django 5.1.15 on 2026-09-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('district', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
                ('is_ceonc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='assessments.alert')),
            ],
        ),
    ]
