# Generated by Django 6.1 on 2026-08-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlcore', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestational_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('bmi', models.FloatField()),
                ('hba1c', models.FloatField()),
                ('fasting_glucose', models.FloatField()),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['visit_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NORMAL', 'Normal'), ('ATTENTION', 'Attention'), ('HIGH_CONCERN', 'High concern'), ('EMERGENCY', 'Emergency')], max_length=16)),
                ('rule_id', models.CharField(blank=True, default='', max_length=64)),
                ('rule_description', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('rules_version', models.CharField(default='v1', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low risk', 'low risk'), ('mid risk', 'mid risk'), ('high risk', 'high risk')], max_length=16)),
                ('probability', models.FloatField(help_text='Confidence for the predicted class (0-1).')),
                ('probabilities', models.JSONField(default=dict, help_text='Per-class probabilities.')),
                ('explanation', models.JSONField(default=dict, help_text='SHAP feature contributions.')),
                ('model_name', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='assessments.assessment')),
                ('model_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='mlcore.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['patient', 'visit_date'], name='assessments_patient_d5c778_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient', 'status'], name='assessments_patient_0d0d17_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category'], name='assessments_categor_1a7966_idx'),
        ),
    ]
