# Generated by Django 6.1 on 2026-08-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.CharField(blank=True, default='', help_text='Provenance URL if available', max_length=512)),
                ('file', models.FileField(blank=True, upload_to='kb/documents/')),
                ('content_text', models.TextField(blank=True, default='', help_text='Extracted full text for text-based sources')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('embedding_backend', models.CharField(default='local', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='kb.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='kb_document_documen_b3816f_idx')],
            },
        ),
    ]
