# Generated by Django 6.1 on 2026-08-19 09:30

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(default=patients.models.generate_patient_code, max_length=16, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, default='', max_length=8)),
                ('gestational_week_at_registration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_due_date', models.DateField(blank=True, null=True)),
                ('gravidity', models.PositiveSmallIntegerField(blank=True, help_text='Total pregnancies, including current.', null=True)),
                ('parity', models.PositiveSmallIntegerField(blank=True, help_text="Births after 20 weeks' gestation.", null=True)),
                ('medical_history_notes', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('healthcare_worker', models.ForeignKey(limit_choices_to={'role': 'HEALTHCARE_WORKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workers', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['patient_code'], name='patients_pa_patient_f7d97c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientassignment',
            unique_together={('healthcare_worker', 'patient')},
        ),
    ]
