# Generated by Django 6.1 on 2026-08-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('REGISTER', 'User registration'), ('PROFILE_UPDATED', 'Profile updated'), ('PASSWORD_CHANGED', 'Password changed'), ('ASSESSMENT_CREATED', 'Assessment created'), ('PREDICTION', 'Prediction generated'), ('RULE_ESCALATION', 'Rule-based escalation'), ('CHAT_ACCESS', 'Chat access'), ('REPORT_GENERATED', 'Report generated'), ('MODEL_TRAINED', 'Model trained'), ('MODEL_ACTIVATED', 'Model activated'), ('KB_UPLOADED', 'Knowledge document uploaded'), ('KB_REINDEXED', 'Knowledge base re-indexed'), ('KB_DELETED', 'Knowledge document deleted'), ('USER_UPDATED', 'User account updated'), ('PATIENT_ASSIGNED', 'Patient assigned to healthcare worker')], max_length=32)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
            },
        ),
    ]
