# Generated by Django 5.1.15 on 2026-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('REGISTER', 'User registration'), ('PROFILE_UPDATED', 'Profile updated'), ('PASSWORD_CHANGED', 'Password changed'), ('ASSESSMENT_CREATED', 'Assessment created'), ('PREDICTION', 'Prediction generated'), ('RULE_ESCALATION', 'Rule-based escalation'), ('CHAT_ACCESS', 'Chat access'), ('REPORT_GENERATED', 'Report generated'), ('MODEL_TRAINED', 'Model trained'), ('MODEL_ACTIVATED', 'Model activated'), ('KB_UPLOADED', 'Knowledge document uploaded'), ('KB_REINDEXED', 'Knowledge base re-indexed'), ('KB_DELETED', 'Knowledge document deleted'), ('USER_UPDATED', 'User account updated'), ('PATIENT_ASSIGNED', 'Patient assigned to healthcare worker'), ('PATIENT_CREATED', 'Patient record created'), ('PATIENT_UPDATED', 'Patient record updated')], max_length=32),
        ),
    ]
